# ----------------------------
# General project configuration
# ----------------------------
root = "FileName"
mode = "official"
ignore_abb_lib = false
scan_root_only = false
debug = false

# ----------------------------
# Paths
# ----------------------------
abb_lib_dir = "${HOME}/Workspace/Libs/SL_Library/"
program_dir = "${HOME}/Workspace/Libs/Programs"
other_lib_dirs = ["${HOME}/Workspace/Libs/1/", "${HOME}/Workspace/Libs/2/"]
